name: visual_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Norbert <email@example.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2
  protobuf: ^0.10.1
  grpc: ^1.0.0

#dev_dependencies:
#  test: ^1.0.0
